---
- hosts: mywebserver
  become: yes
  tasks: 
      - name: i want to install java jdk8 on ubuntu
        apt:
            name: "{{myjavajdk8onubuntu}}"
            state: present 
        when: ansible_os_family=="Debian"
      - name: i want to install java jdk8 on redhat 
        yum:
            name: "{{myjavajdk8onredhat}}"
            state: present 
        when: ansible_os_family=="RedHat"          