---
- hosts: 13.115.162.111
  become: yes
  tasks:
      - name: i want to execute linux cmd 
        command: hostname -f 
        register: myresult 

      - name: i want to display linux output 
        debug:
            msg: "{{myresult}}"  